# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MF_wDlGYqlFSqA7KUTLA8nFxMq8IN660

Let's begin with defining random.
"""

import random
def random_response(responses):
    return random.choice(responses)

"""Let's Generate some responses accordingly."""

GREETING_RESPONSES = ["Hello!", "Hi there!", "Hey!", "Greetings!","YO!",]

HOW_ARE_YOU_RESPONSES = ["I'm doing well, thank you!", "I'm fine, thanks for asking.", "All good on my end!"]

BYE_RESPONSES = ["Goodbye!", "Take Care!", "See you later!","See You Soon!"]

UNKNOWN_RESPONSES = ["I'm sorry, I don't understand.", "I'm sorry, I don't have any clue about what you are asking.", "I'm not sure what you mean.",]

def chatbot_response(user_input):
    if "hello" in user_input.lower():
        return random_response(GREETING_RESPONSES)
    elif "how are you" in user_input.lower():
        return random_response(HOW_ARE_YOU_RESPONSES)
    elif "bye" in user_input.lower():
        return random_response(BYE_RESPONSES)
    else:
        return random_response(UNKNOWN_RESPONSES)

"""Let's define the Main Function."""

def main():
    print("Welcome to Rule Based Chatbot")
    print("Type 'bye' to exit.")

    while True:
        user_input = input("You: ")
        if user_input.lower() == 'bye':
            print("Bot:", chatbot_response(user_input))
            break
        else:
            print("Bot:", chatbot_response(user_input))

if __name__ == "__main__":
    main()